### ISSUE TITLE
add Columbia blue...

### ISSUE THREAD

**Issue by sbillinge** [Billingegroup/bg-mpl-stylesheets#55]
...add it to the Colors but not the cycler.

it has hex B9D9EB
per https://visualidentity.columbia.edu/branding

**Comment by sbillinge** [comment]
let's call it `columbia_blue`

**Comment by bobleesj** [comment]
Shall close as https://github.com/Billingegroup/bg-mpl-stylesheets/pull/56 merged

**Comment by bobleesj** [comment]
Okay, please close this... I will use the special keywords next time at the top comment. @sbillinge
