### ISSUE TITLE
add list of colors available in colors to docs

### ISSUE THREAD

**Issue by sbillinge** [Billingegroup/bg-mpl-stylesheets#57]
currently the docs are in readme which is fine for now

**Comment by bobleesj** [comment]
Shall close as https://github.com/Billingegroup/bg-mpl-stylesheets/pull/58 merged

**Comment by sbillinge** [comment]
We must not forget to write 'closes #57' in the top comment section of the PR.  Then it will automatically close when that is merged

**Comment by bobleesj** [comment]
> We must not forget to write 'closes #57' in the top comment section of the PR. Then it will automatically close when that is merged

Okay will do.
