### ISSUE TITLE
Remove requirements/examples.txt in 0.4.2

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/bg-mpl-stylesheets#59]
`requirements/examples.txt` contains

```
numpy
diffpy.utils
```

**Comment by bobleesj** [comment]
https://github.com/Billingegroup/bg-mpl-stylesheets/blob/main/requirements/examples.txt

**Comment by sbillinge** [comment]
Why do you want to remove this?

**Comment by bobleesj** [comment]
Closing this. I see that it is being used in `example/plot.py`

```python
import matplotlib.pyplot as plt
from diffpy.utils.parsers.loaddata import loadData
```
