### ISSUE TITLE
Remove .DS_Store and Fix Codecov being unknown

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/bg-mpl-stylesheets#61]
1. There is a `.DS_Store` [file](https://github.com/Billingegroup/bg-mpl-stylesheets/blob/main/.DS_Store) at the top directory even though it's within `.gitignore`:

```
# mac
.DS_Store
```

Shall remove it?

2. Codecov remains "unknown" in `README.md`:

<img width="429" alt="Screenshot 2024-09-06 at 6 53 53 AM" src="https://github.com/user-attachments/assets/efe9e019-6da1-4a68-ba0d-1c3f3e63c1e7">

Should we fix it? @sbillinge

**Comment by sbillinge** [comment]
yes, we can do `git rm` and get rid of it.

**Comment by sbillinge** [comment]
no need for a news for that.
